import json
import logging

logger = logging.getLogger(__name__)


def generate_replay_test(crash) -> str:
    """
    Generate a pytest that reproduces the crash.
    Returns test code string. Never raises.
    """
    logger.info(f"Generating replay test for {crash.endpoint}")
    try:
        endpoint = crash.endpoint or "POST /user"
        # Extract method and path
        parts = endpoint.split(" ", 1)
        method = parts[0].lower() if len(parts) > 1 else "post"
        path = parts[1] if len(parts) > 1 else endpoint

        payload = crash.request_payload or '{"cart_id": "c123"}'
        # Ensure payload is valid JSON string
        try:
            payload_dict = json.loads(payload) if isinstance(payload, str) else payload
            payload_str = json.dumps(payload_dict)
        except (json.JSONDecodeError, TypeError):
            payload_str = '{"cart_id": "c123"}'

        test_code = f'''import httpx
import pytest


def test_runtimeguard_replay_incident():
    """
    Replay test: proves the bug exists (should fail on unfixed code, pass on fixed code).
    Generated by RuntimeGuard AI from production crash.
    
    Original crash: {crash.exception_type}: {crash.exception_message}
    File: {crash.primary_file}:{crash.line_number}
    Function: {crash.function_name}
    """
    with httpx.Client(base_url="http://localhost:8001") as client:
        response = client.{method}("{path}", json={payload_str})
        # After fix: endpoint should NOT return 500
        assert response.status_code != 500, (
            f"Endpoint still crashing: {{response.status_code}} {{response.text}}"
        )
'''
        logger.info("Replay test generated successfully")
        return test_code
    except Exception as e:
        logger.warning(f"Failed to generate replay test: {e}")
        return '''import httpx

def test_runtimeguard_replay_incident():
    """Fallback replay test."""
    with httpx.Client(base_url="http://localhost:8001") as client:
        response = client.post("/user", json={"cart_id": "c123"})
        assert response.status_code != 500
'''
