"""
Test generator - creates tests based on incident type.
"""
from typing import Dict, Any, Optional


def generate_tests(incident_type: str, incident_bundle: Dict) -> Optional[str]:
    """Generate test code for the detected incident."""

    if incident_type == "dependency_incompatibility":
        return _gen_sdk_compat_test(incident_bundle)
    elif incident_type == "runtime_config_drift":
        return _gen_config_test(incident_bundle)
    elif incident_type == "visual_user_flow_failure":
        return _gen_playwright_test(incident_bundle)
    elif incident_type == "frontend_backend_contract_mismatch":
        return _gen_contract_test(incident_bundle)
    return None


def _gen_sdk_compat_test(bundle: Dict) -> str:
    return '''// Generated by RuntimeGuard AI
// Test: Payment SDK v3 compatibility
// Verifies that error handling works with both v2 and v3 SDK error shapes

describe('Payment SDK Compatibility', () => {
  test('handles SDK v3 error shape (error_code)', () => {
    // SDK v3 error shape
    const err = { error_code: 'CARD_DECLINED', error_message: 'Declined', message: 'Payment failed' }
    const code = err.code || err.error_code || 'UNKNOWN_ERROR'
    expect(code).toBe('CARD_DECLINED')
  })

  test('handles SDK v2 error shape (code) - backwards compat', () => {
    // SDK v2 error shape (legacy)
    const err = { code: 'CARD_DECLINED', message: 'Payment failed' }
    const code = err.code || err.error_code || 'UNKNOWN_ERROR'
    expect(code).toBe('CARD_DECLINED')
  })

  test('handles missing error code gracefully', () => {
    // Neither v2 nor v3 shape
    const err = { message: 'Payment failed' }
    const code = err.code || err.error_code || 'UNKNOWN_ERROR'
    expect(code).toBe('UNKNOWN_ERROR')
  })
})
'''


def _gen_config_test(bundle: Dict) -> str:
    return '''// Generated by RuntimeGuard AI
// Test: Runtime config validation
// Verifies that missing env vars are caught at startup

describe('Runtime Config Validation', () => {
  const originalEnv = process.env

  beforeEach(() => {
    jest.resetModules()
    process.env = { ...originalEnv }
  })

  afterAll(() => {
    process.env = originalEnv
  })

  test('throws on missing PAYMENT_PROVIDER_KEY', () => {
    delete process.env.PAYMENT_PROVIDER_KEY
    expect(() => {
      if (!process.env.PAYMENT_PROVIDER_KEY) {
        throw new Error('PAYMENT_PROVIDER_KEY is required but not set')
      }
    }).toThrow('PAYMENT_PROVIDER_KEY is required')
  })

  test('succeeds when all required env vars present', () => {
    process.env.PAYMENT_PROVIDER_KEY = 'test-key'
    expect(() => {
      if (!process.env.PAYMENT_PROVIDER_KEY) {
        throw new Error('PAYMENT_PROVIDER_KEY is required')
      }
    }).not.toThrow()
  })
})
'''


def _gen_playwright_test(bundle: Dict) -> str:
    url = bundle.get('deployment_url', 'http://localhost:5173')
    return f'''// Generated by RuntimeGuard AI
// Test: Visual flow verification
// Verifies that Pay Now button triggers checkout flow

const {{ test, expect }} = require('@playwright/test')

test('Pay Now button initiates checkout flow', async ({{ page }}) => {{
  await page.goto('{url}')

  // Button should be visible
  const payBtn = page.locator('button:has-text("Pay Now")')
  await expect(payBtn).toBeVisible()

  // Set up response listener
  let responseReceived = false
  page.on('response', response => {{
    if (response.url().includes('/api/payment')) {{
      responseReceived = true
      // Should not be a server error
      expect(response.status()).toBeLessThan(500)
    }}
  }})

  // Click Pay Now
  await payBtn.click()

  // Wait for network
  await page.waitForTimeout(2000)

  // Should have received a payment API response
  expect(responseReceived).toBe(true)

  // Error message should be user-friendly (not a 500 server error)
  const errorText = await page.locator('.error-message, [data-testid="error"]').textContent().catch(() => '')
  expect(errorText).not.toContain('Internal Server Error')
}})
'''


def _gen_contract_test(bundle: Dict) -> str:
    return '''// Generated by RuntimeGuard AI
// Test: API contract verification

describe('API Contract', () => {
  test('frontend API endpoints match backend routes', async () => {
    const frontendEndpoints = ['/api/payment/create-order']
    const backendRoutes = ['/api/payment/create-order']

    for (const endpoint of frontendEndpoints) {
      expect(backendRoutes).toContain(endpoint)
    }
  })
})
'''
